set_entity_script(self, "");
remove_item("ITEM_0002");
replace_navigation(self, INTERACT_ONLY, WALK_AND_INTERACT);
put_entity("bookcase", "bookcase_target");
replace_navigation(self, WALK_AND_INTERACT, NONE);
play_sound("secret");
play_animation(entity["secret_wall"], "open");
show_group("dungeon_room2");
set_global_property("dungeon_room2_visible", true);
wait(1.25);
remove_entity(entity["secret_wall"])
